Repository Datenschule/jedeschule-scraper, pull requests merged in 2020-02, with the labels that each got.

#57 HB: add school ID and director
  jedeschule/spiders/bremen.py
Labels: state:HB

#53 update Sachsen-Anhalt crawler
  jedeschule/spiders/sachsen_anhalt.py
Labels: state:ST

#48 Add basic database pipeline
  README.md
  alembic.ini
  alembic/README
  alembic/__init__.py
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/7debef0e3f50_create_initial_school_table.py
  alembic/versions/__init__.py
  jedeschule/pipelines/__init__.py
  jedeschule/pipelines/db_pipeline.py
  jedeschule/pipelines/school_pipeline.py
  jedeschule/settings.py
  requirements.txt
Labels: Pipeline, enhancement
