Repository Datenschule/jedeschule-scraper, pull requests merged in 2021-01, with the labels that each got.

#90 Updated Schleswig-Holstein spider
  jedeschule/spiders/schleswig_holstein.py
Labels: state:SH

#96 Rebase new Sachsen scraper on latest master, drop unused methods
  jedeschule/spiders/sachsen.py
Labels: state:SN

#81 Updated Berlin scraper
  jedeschule/spiders/berlin.py
Labels: state:BE

#83 Updated Brandenburg spider
  jedeschule/spiders/brandenburg.py
Labels: state:BB

#97 Updated Bremen spider - 84 rebased
  jedeschule/spiders/bremen.py
Labels: state:HB

#98 New Hessen Spider rebased
  jedeschule/spiders/hessen.py
Labels: state:HE

#100 Added fax, school_type and legal_status to normalize()
  jedeschule/spiders/bayern.py
Labels: state:BY

#101 Update Saarland spider (rebased)
  jedeschule/spiders/saarland.py
Labels: state:SL

#110 Scrape provider for NRW scrapers
  jedeschule/spiders/nordrhein_westfalen.py
  jedeschule/spiders/nordrhein_westfalen_helper.py
Labels: state:NW

#73 [HB] Exit early if page contains no data
  jedeschule/spiders/bremen.py
Labels: state:HB
